---
title: Instructor bios
output: html_document
---

#### Eugen Buehler, PhD

Dr. Buehler is a bioinformatician with wide-ranging experience in the computational analysis
of genomic studies. He holds a PhD in Computer Science with earlier training in Physics. He
has been using R for over 10 years primarily in the areas of computational biology and 
bioinformatics. He has over 20 years experience working in academia, the pharmaceutical
industry and government, and specializes in mathematical modeling, statistics, machine 
learning, and the analysis and integration of large-scale biological data sets. 

#### Abhijit Dasgupta, PhD

Dr. Dasgupta is a biostatistician and data scientist with experience in statistical 
modeling and machine learning, bioinformatics, optimization, signal processing, and 
data visualization. He holds a PhD in Biostatistics with earlier training in Mathematical
Statistics. He has been using R for over 18 years for a wide variety of applications in biomedical 
research, as well as for data-driven reports and presentations. He co-organizes
the [Statistical Programming DC](http://www.meetup.com/stats-prog-dc) meetup (formerly R Users Group DC)
and serves on the Board of [Data Community DC](http://www.datacommunitydc.org). He 
regularly gives workshops and webinars on using R and Python for data analysis. 