---
title: "Bioinformatics 339: Practical R"
author: "Abhijit Dasgupta & Eugen Buehler"
date: "Fall 2016"
output: html_document
---

<a href="http://www.r-project.org" target="_blank">R</a> is one of the most popular programming languages for 
data science and statistics. It is a free and open source language available for 
all major operating systems. It is extensible through a packaging system that has resulted
in over 9000 user-contribued packages available on [CRAN](http://cran.r-project.org). 

In this course we will provide a practical approach to learning R using examples, with
the intention to get you using R for your data analyses, data visualization and reporting 
as quickly as possible. We will try to avoid the more esoteric and "computer science-y" aspects
of this programming language. We hope this approach and personal practice enables 
you to get started using R for your own work, find resources you may need beyond this
course to help you answer your particular questions, and develop workflows for your data
analyses that allow you to generate tables and figures for research papers, for example. 

The instructors have both been using R in their daily work at NIH and earlier for
many many years and have a pretty detailed knowledge of R's advantages, pitfalls, tricks 
and shortcuts. Don't hesitate to reach out and ask your questions. 

-----

<p style="font-size: 80%"> This website is written using R, <a href="http://rmarkdown.rstudio.com/index.html" target="_blank">R Markdown</a> and various packages provided by <a href="http://www.rstudio.com" target="_blank">RStudio</a>. 
The source code is available on <a href="https://github.com/araastat/BIOF339_PracticalR/tree/gh-pages" target="_blank">GitHub</a> </p>