---
title: "Lectures"
date: "Fall 2018"
output: html_document
---

Last updated: `r format(Sys.time(), '%b %d, %Y (%l:%M%p %Z)')`

------

<div style = 'border: 1px solid black;vertical-align:center;padding-top: 1em;padding-left:1em;'>
New blog post (2018/11/16): [Function documentation](blog/public/2018/11/16/function-documentation/index.html)
</div>

-------

### Lecture 1 : Introduction

[Presentation](Lectures/lecture_intro.pdf){target="_blank"}

<a href="Lectures/lecture_intro_files/lecture_intro_Exercises.html" target="_blank">Practice Exercises for Lecture 1</a> (<a href="Lectures/lecture_intro_files/lecture_intro_ExercisesSolution.html" target="_blank">Solutions</a>)

Supplemental Material

+ Installing R: <a href="http://cran.r-project.org" target="_blank">http://cran.r-project.org</a>
+ Installing RStudio: <a href="https://www.rstudio.com/products/rstudio/download3/" target="_blank" >http://www.rstudio.com/products/rstudio</a>
+ Searching for information about R: <a href="http://www.rseek.org" target="_blank">rseek.org</a>

In-built datasets in R: `data()`

### Lecture 2 : Data Frames and other structures

<a href="Lectures/lecture_dataframe.html" target="_blank">Presentation</a> ([PDF](Lectures/lecture_dataframe.pdf){target="_blank"})

<a href="Lectures/lecturedataframe_files/lecture_dataframe_practicum.html" target="_blank">Practicum</a> (<a href="Lectures/lecturedataframe_files/lecture_dataframe_practicum_solutions.html" target="_blank">Solution</a>)

Supplemental Material

+ [A primer on R Notebooks](Lectures/lecturedataframe_files/RNotebook.html){target="_blank"}

### Lecture 3 : Introduction to the tidyverse

<a href="Lectures/lecture_tidyverse.html" target = "_blank">Presentation</a> ([PDF](Lectures/lecture_tidyverse.pdf){target="_blank"})

<a href="Lectures/lecturetidyverse_files/lecture_tidyverse_Practicum.html" target="_blank">Practicum</a> ([Solution](Lectures/lecturetidyverse_files/lecture_tidyverse_Practicum_Solutions.html){target="_blank"})

Supplemental material

+ [`dplyr` cheatsheet](https://www.rstudio.com/resources/cheatsheets/#dplyr)

### Lecture 4 : Data Visualization

<a href="Lectures/lecture_visualization.html" target = "_blank">Presentation</a> | [PDF](Lectures/lecture_visualization.pdf){target="_blank"} | [Audio (partial)](https://www.dropbox.com/s/l9vsn7gcxnz3fza/DataViz_2018.MP3?dl=1)

[R Markdown file](Lectures/lecture_visualization.Rmd){target="_blank"}

Supplemental material

#### Online resources

+ The ggplot [website](http://docs.ggplot2.org){target="_blank"} has many resources to help create visualizations
+ [Cheatsheet](https://www.rstudio.com/wp-content/uploads/2015/03/ggplot2-cheatsheet.pdf){target="_blank"}
+ The [R Graph Gallery](https://www.r-graph-gallery.com/){target="_blank"}
+ There are a lot of blogs showing many capabilities of ggplot2
+ [StackOverflow](https://stackoverflow.com/questions/tagged/r) is the place for Q & A. Their tag is `r`. They also have tags `ggplot2`, `ggpubr` and `cowplot`. 

#### Other packages

+ The [`cowplot`](http://cran.rstudio.com/package=cowplot) and [`ggpubr`](https://cran.r-project.org/package=ggpubr) packages provide several improvements on ggplot2, including more themes and an easy way to put several graphs together in a panel

### Lecture 5 : Statistics

<a href="Lectures/lecture_summaries.html" target = "_blank">Presentation</a> ([PDF](Lectures/lecture_summaries.pdf){target="_blank"})

<a href="Lectures/lecture_summaries_files/lecture_summaries_Practicum.html" target="_blank">Practicum</a> ([Solution](Lectures/lecture_summaries_files/lecture_summaries_PracticumSolution.html){target="_blank"})

### Lecture 6 : Data Input and Output

<a href="Lectures/lecture_dataio.html" target = "_blank">Presentation</a>  | [PDF](Lectures/lecture_dataio.pdf){target="_blank"} | [Audio](https://www.dropbox.com/s/knd5cegclbm352l/DataIO_2018.MP3?dl=1)

<a href="Lectures/lecturedataio_files/lecture_dataio_Practicum.html" target="_blank">Practicum</a> ([Solution](Lectures/lecturedataio_files/lecture_dataio_PracticumSolution.html){target="_blank"})

#### Other resources

+ Pages for [`readr`](http://readr.tidyverse.org){target="_blank"}, [`rio`](https://cran.r-project.org/web/packages/rio/README.html){target="_blank"} and [`readxl`](http://readxl.tidyverse.org){target="_blank"}
+ The [`openxlsx`](https://cran.r-project.org/web/packages/openxlsx/index.html){target="_blank"} package for writing to Excel directly. Read the vignettes in the middle of the page for examples of the power of this package
+ A comparison of the [`reshape2` and `tidyr` packages](http://www.milanor.net/blog/reshape-data-r-tidyr-vs-reshape2/){target="_blank"}
+ Hadley Wickham on ["Data analyis pipelines"](https://www.rstudio.com/resources/webinars/pipelines-for-data-analysis-in-r/){target="_blank"}

### Lecture 7: Joins, Split-Apply-Combine, and MCPs

[Presentation](Lectures/lecture_joins_sac.html){target="_blank"} ([PDF](Lectures/lecture_joins_sac.pdf){target='_blank"})

[Practicum](Lectures/lecture_joins_sac_data/JoinsPracticum.html){target="_blank"} | [Solution](Lectures/lecture_joins_sac_data/JoinsPracticumSolution.html)

#### Other resources
+ Jenny Bryan's [purrr tutorials](https://jennybc.github.io/purrr-tutorial/){target="_blank"}
+ Jenny Bryan's excellent talk on [list-columns](https://speakerdeck.com/jennybc/putting-square-pegs-in-round-holes-using-list-cols-in-your-dataframe){target="_blank"}
+ [A very nice listing of purrr-related posts](https://maraaverick.rbind.io/2017/09/-purrr-ty-posts/)

### Lecture 8: Statistical Modeling

[Presentation](Lectures/lecture_modeling.html){target='_blank'}

[Practicum](Lectures/lecture5_files/Practicum5.html){target="_blank"} | [Solution](Lectures/lecture5_files/Practicum5_Solution.html){target="_blank"}

#### Other resources

+ An Introduction to Statistical Learning [Course and Book](http://www-bcf.usc.edu/~gareth/ISL/index.html) 

### Lecture 9: Building Functions

[Presentation](Lectures/lecture_functions.html){target='_blank'} | [PDF](Lectures/lecture_functions.pdf){target="_blank"}

Parkin Translocation siRNA Screening [Data from Lecture](Lectures/lecture_functions_data/nature.parkin.gw.xlsx)

[Practicum](Lectures/lecture_functions_files/Practicum_Functions.html){target="_blank"} |
[Solution](Lectures/lecture_functions_files/Practicum_Functions_Solution.html){target="_blank"}

### Lecture 10: Project organization

[Presentation](Lectures/lecture_bestpractice.html){target='_blank'}

### Lecture 11: Bioconductor

[Presentation](Lectures/lecture_bioconductor.html){target='_blank'} | [PDF](Lectures/lecture_bioconductor.pdf)

[Practicum](Lectures/practicum_bioconductor.html){target="_blank"} |
[Solution](Lectures/practicum_bioconductor_solution.html){target="_blank"}

### Lecture 12: Publication-ready graphics

[Presentation](Lectures/lecture_pubgraphics.html){target="_blank"}