---
title: "Assignment 2"
author: "BIOF 339"
date: "September 26, 2016"
output: html_document
---

1. The `pbc` data set in the package `survival` contains data on patients with primary biliary cirrhosis from the Mayo Clinic between 1974 and 1984. 

    1. Access the data (you have to load the package `survival` first)
    2. Identify which variables are discrete/categorical and which are continuous
    3. Create univariate visualizations (histograms/density plots/barplots) for each clinical variable
    4. Create bivariate visualizations (boxplot/violinplot/scatter plots) as appropriate
    5. For the scatter plots, add a line representing the relationship between the variables
    6. Create a facetted plot showing the distribution of patient age by sex
    7. Create a boxplot showing how platelet count is related to stage
    8. Create a grouped plot showing how cholesterol and albumin are related, grouped by sex
    
2. (Extra credit)
    1. Create a plot showing how platelet count is related with stage, facetted by sex
    2. Create a plot showing how alk.phos and ast are related, grouped by sex and facetted by stage.
    