---
title: "Lecture 1 Activities"
author: "Eugen Buehler"
date: "September 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup of your computer

If you have not already, you will want to install R and RStudio on a computer, preferably one that you can bring to class.  It is possible that you will need to to submit a request to your local IT support in order to install this software, if you don't have permission to install things yourself.  Install R first (which RStudio depends on), and then RStudio.

http://lib.stat.cmu.edu/R/CRAN/

https://www.rstudio.com/products/rstudio/download/

## Class Exercises

1.  Use the help function to learn about the “colon operator”.  Type help(“:”).  If you’re using RStudio, you could also type : in the Help pane search box.

2.  Using what you learned from the help page for the colon operator, create a variable called first10 with the numbers 1 through 10 in it.

3.  Now try multiplying firstTen by 10 (firstTen * 10).  What was the result?

4.  Using the colon operator and the sum function, find out what the sum of the integers from 1 to 1000 is.  

5.  Create a variable called myFavoritePies and put the names of your favorite pies in it (if you have no favorite pies, reconsider your life priorities).

6.  Change myPies so that it contains your favorite pies AND tells R about some of the other kinds of pies that exist but are not your favorite.

7.  Use the ls function to see the variables you have created.  You can also view the variables you have created in the “environment” tab in the upper right hand panel of RStudio.

8.  Use the history function to view the commands you have typed (or just click on the “History” tab in the upper right panel of RStudio).  Double click on the line you used to calculate the answer to question 4.  Now modify the command to find the sum of the EVEN numbers from 1 to 1000.
